# Generated by Django 4.2.1 on 2023-10-22 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=64)),
                ('image', models.ImageField(blank=True, default='media/default.jpg', upload_to='images')),
                ('club', models.CharField(max_length=64)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=10800))),
            ],
        ),
    ]
