# Generated by Django 4.2.1 on 2023-10-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_events_time_alter_events_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='category',
            field=models.CharField(default='general', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='allfurnitures/users/default.jpg', upload_to='users'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlists', to='events.events'),
        ),
    ]
