# Generated by Django 4.2.1 on 2023-10-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_events_category_user_image_user_mobile_user_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='tickets',
            field=models.IntegerField(default=100),
        ),
    ]
